version: '3.8'

services:
  # Layanan untuk PHP
  php:
    build: .
    container_name: php-container
    ports:
      - "8080:80"       # Mengakses aplikasi PHP di http://localhost:8080
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  # Layanan untuk MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_warung_meduro
      MYSQL_USER: user
      MYSQL_PASSWORD: warung_meduro
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql-data:/var/lib/mysql
      
      
    ports:
      - "3306:3306"

    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-container
      PMA_USER: user
      PMA_PASSWORD: warung_meduro
    networks:
      - app-network

   
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
